version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tre-forward"
    schedule:
      interval: "daily"
    target-branch: "target-branch"  
  - package-ecosystem: "docker"
    directory: "/tre-forward"
    schedule:
      interval: "daily"
